import 'package:intl/intl.dart';

/// Centralized Date & Time Formatter for Secure360 Mobile Guard Application
///
/// Follows Global Display Standards:
/// - Date only: dd-MMM-yy (e.g. 18-Sep-26)
/// - Date & Time: dd-MMM-yy hh:mm AM/PM (e.g. 18-Sep-26 05:45 PM)
/// - Time only: hh:mm AM/PM (e.g. 05:45 PM, 08:00 AM)
/// - Date range: dd-MMM-yy → dd-MMM-yy (e.g. 01-Jan-26 → 31-Dec-26)
/// - Shift range: hh:mm AM/PM - hh:mm AM/PM (e.g. 08:00 AM - 04:00 PM)
class TimeFormatter {
  static final DateFormat _dateFormat = DateFormat('dd-MMM-yy');
  static final DateFormat _dateTimeFormat = DateFormat('dd-MMM-yy hh:mm a');
  static final DateFormat _timeFormat = DateFormat('hh:mm a');

  /// Standard application timezone offset: Asia/Kolkata (IST = UTC +05:30)
  static const Duration istOffset = Duration(hours: 5, minutes: 30);

  /// Parse dynamic input (String, DateTime, int) into an IST-normalized DateTime.
  ///
  /// Handling by input type:
  /// 1. SQL Datetime / Date without timezone offset (e.g. "2026-09-18 13:00:00", "2026-09-18"):
  ///    Generated by MySQL / backend in IST. Wall-clock values ALREADY represent Indian Standard Time.
  ///    Preserved directly without adding or subtracting any offset (prevents double conversion).
  ///
  /// 2. ISO 8601 Strings with explicit timezone designator ('Z' or "+/-HH:mm"):
  ///    E.g. "2026-09-18T07:30:00Z" or "2026-09-18T13:00:00+05:30"
  ///    Parsed in UTC, then shifted by +5:30 to derive IST.
  ///
  /// 3. Epoch Timestamps (int):
  ///    Milliseconds or seconds since Unix epoch (absolute UTC).
  ///    Parsed as UTC and shifted by +5:30 to derive IST.
  ///
  /// 4. DateTime instances (e.g. DateTime.now()):
  ///    Converted to UTC, then shifted by +5:30 to derive IST regardless of device local clock.
  static DateTime? parseDateTime(dynamic input) {
    if (input == null) return null;

    // 1. If already a DateTime: convert to UTC, then apply IST offset
    if (input is DateTime) {
      final utc = input.toUtc();
      final ist = utc.add(istOffset);
      return DateTime.utc(ist.year, ist.month, ist.day, ist.hour, ist.minute, ist.second, ist.millisecond);
    }

    // 2. If integer (epoch timestamp)
    if (input is int) {
      final ms = input < 10000000000 ? input * 1000 : input;
      final utc = DateTime.fromMillisecondsSinceEpoch(ms, isUtc: true);
      final ist = utc.add(istOffset);
      return DateTime.utc(ist.year, ist.month, ist.day, ist.hour, ist.minute, ist.second);
    }

    if (input is String) {
      final trimmed = input.trim();
      if (trimmed.isEmpty || trimmed == '0000-00-00' || trimmed == '0000-00-00 00:00:00') {
        return null;
      }

      // 3. Pure time strings: "08:00:00", "13:00", etc.
      if (RegExp(r'^\d{1,2}:\d{2}(:\d{2})?$').hasMatch(trimmed)) {
        final parts = trimmed.split(':');
        final h = int.tryParse(parts[0]) ?? 0;
        final m = int.tryParse(parts[1]) ?? 0;
        final s = parts.length > 2 ? (int.tryParse(parts[2]) ?? 0) : 0;
        return DateTime.utc(1970, 1, 1, h, m, s);
      }

      // 4. ISO string with explicit timezone offset ('Z' or "+/-HH:mm")
      final hasExplicitTz = trimmed.endsWith('Z') ||
          trimmed.endsWith('z') ||
          RegExp(r'[+-]\d{2}:?\d{2}$').hasMatch(trimmed);

      if (hasExplicitTz) {
        try {
          final parsed = DateTime.parse(trimmed).toUtc();
          final ist = parsed.add(istOffset);
          return DateTime.utc(ist.year, ist.month, ist.day, ist.hour, ist.minute, ist.second);
        } catch (_) {}
      }

      // 5. Timestamp WITHOUT timezone (e.g. "2026-09-18 13:00:00", "2026-09-18", "2026-09-18T13:00:00")
      // These strings originate from MySQL / backend in IST. Their values ALREADY represent Indian time.
      final clean = trimmed.replaceAll('/', '-');
      final match = RegExp(r'^(\d{4})-(\d{1,2})-(\d{1,2})(?:[ T](\d{1,2}):(\d{2})(?::(\d{2}))?)?').firstMatch(clean);
      if (match != null) {
        final year = int.parse(match.group(1)!);
        final month = int.parse(match.group(2)!);
        final day = int.parse(match.group(3)!);
        final hour = match.group(4) != null ? int.parse(match.group(4)!) : 0;
        final minute = match.group(5) != null ? int.parse(match.group(5)!) : 0;
        final second = match.group(6) != null ? int.parse(match.group(6)!) : 0;
        return DateTime.utc(year, month, day, hour, minute, second);
      }

      // Fallback: try DateTime.tryParse
      final fallback = DateTime.tryParse(trimmed);
      if (fallback != null) {
        if (fallback.isUtc) {
          final ist = fallback.add(istOffset);
          return DateTime.utc(ist.year, ist.month, ist.day, ist.hour, ist.minute, ist.second);
        }
        return DateTime.utc(fallback.year, fallback.month, fallback.day, fallback.hour, fallback.minute, fallback.second);
      }
    }

    return null;
  }

  /// Formats date only: dd-MMM-yy (e.g. 18-Sep-26)
  static String formatDate(dynamic dateInput, {String fallback = '—'}) {
    final dt = parseDateTime(dateInput);
    if (dt == null) return fallback;
    return _dateFormat.format(dt);
  }

  /// Formats date and time: dd-MMM-yy hh:mm AM/PM (e.g. 18-Sep-26 05:45 PM)
  static String formatDateTime(dynamic dateTimeInput, {String fallback = '—'}) {
    final dt = parseDateTime(dateTimeInput);
    if (dt == null) return fallback;
    final formatted = _dateTimeFormat.format(dt);
    return _uppercaseAmPm(formatted);
  }

  /// Formats time only: hh:mm AM/PM (e.g. 05:45 PM, 08:00 AM)
  static String formatTime(dynamic timeInput, {String fallback = '—'}) {
    if (timeInput == null) return fallback;
    final trimmed = timeInput.toString().trim();
    if (trimmed.isEmpty) return fallback;

    // Avoid double conversion if already formatted with AM/PM
    if (trimmed.toUpperCase().contains('AM') || trimmed.toUpperCase().contains('PM')) {
      return _uppercaseAmPm(trimmed);
    }

    final dt = parseDateTime(trimmed);
    if (dt != null) {
      return _uppercaseAmPm(_timeFormat.format(dt));
    }

    // Fallback manual parse for HH:MM:SS or HH:MM
    final parts = trimmed.split(':');
    if (parts.length >= 2) {
      final hour = int.tryParse(parts[0]);
      final minute = int.tryParse(parts[1]);
      if (hour != null && minute != null) {
        final period = hour >= 12 ? 'PM' : 'AM';
        var hour12 = hour % 12;
        if (hour12 == 0) hour12 = 12;
        final hrStr = hour12.toString().padLeft(2, '0');
        final minStr = minute.toString().padLeft(2, '0');
        return '$hrStr:$minStr $period';
      }
    }

    return trimmed;
  }

  /// Formats date range: dd-MMM-yy → dd-MMM-yy (e.g. 01-Jan-26 → 31-Dec-26)
  static String formatDateRange(dynamic start, dynamic end, {String fallback = '—'}) {
    final startStr = formatDate(start, fallback: '');
    final endStr = end != null ? formatDate(end, fallback: '') : 'Ongoing';
    if (startStr.isEmpty && (endStr.isEmpty || endStr == 'Ongoing')) return fallback;
    if (startStr.isEmpty) return endStr;
    return '$startStr → $endStr';
  }

  /// Formats shift time range: hh:mm AM/PM - hh:mm AM/PM (e.g. 08:00 AM - 04:00 PM)
  static String formatTimeRange(dynamic start, dynamic end, {String fallback = '—'}) {
    final startFormatted = formatTime(start, fallback: '');
    final endFormatted = formatTime(end, fallback: '');
    if (startFormatted.isEmpty && endFormatted.isEmpty) return fallback;
    if (startFormatted.isEmpty) return endFormatted;
    if (endFormatted.isEmpty) return startFormatted;
    return '$startFormatted - $endFormatted';
  }

  /// Ensures AM/PM indicators are displayed in uppercase
  static String _uppercaseAmPm(String text) {
    return text.replaceAll('am', 'AM').replaceAll('pm', 'PM');
  }
}
